apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/PenPeen/mail-worker-k8s
  password: ${GITHUB_PAT}
  username: ${GITHUB_USERNAME}